@startuml
hide footbox
title 归还图书顺序图
actor 图书管理员 as user
activate user
user->读者:读者是否登录
activate 读者
deactivate 读者
loop 归还操作主体
user->借书记录:查询借阅信息
activate 借书记录
借书记录->馆藏资源品种:选中归还馆藏资源
activate 馆藏资源品种
馆藏资源品种->图书:选中目标图书
activate 图书
deactivate 图书
deactivate 馆藏资源品种
deactivate 借书记录
user->读者:获取读者信息
activate 读者
读者->馆藏资源品种:归还馆藏资源
activate 馆藏资源品种
馆藏资源品种->图书:增加图书库存
activate 图书
图书->还书记录:增加还书记录
activate 还书记录
deactivate 还书记录
deactivate 图书
deactivate 馆藏资源品种
deactivate 读者
user->读者:读者借阅限量+1
activate 读者
deactivate 读者
end
loop 逾期操作主体
user->还书记录:是否逾期
activate 还书记录
deactivate 还书记录
user->读者:获取读者信息
activate 读者
deactivate 读者
user->图书:获取图书信息
activate 图书
deactivate 图书
user->逾期记录:增加逾期记录（读者编号，书籍编号，应还时间，归还时间，逾期金额等）
activate 逾期记录
deactivate 逾期记录
end
@enduml