@startuml
package bookManageSystem <<Frame>> #f5f5f5{
class 逾期罚款{
    逾期id
    读者编号
    读者真实姓名
    书籍名称
    书籍编号
    借阅时间
    应还时间
    归还时间
    逾期金额
}
class 还书{
    读者编号
    书籍编号
    借阅时间
    应还时间
    归还时间
}
class 借书{
    读者编号
    书籍编号
    借阅时间
    应还时间
}
class 注册登录{
    用户名
    密码
    验证码
    登录()
    注册()
}
class 读者{
    用户id
    用户名
    密码
    头像地址
    昵称
    性别
    出生年月
    学号
    已借数量
    注册时间
    真实姓名
}
class 管理员{
    管理员id
    用户名
    密码
    真实姓名
    性别
    入职时间
}
class 图书{
    书籍编号
    书籍名称
    类型
    作者
    出版社
    出版日期
    单价
    入库日期
    是否可借
}
    读者"*"--"*"借书:借书
    读者"*"--"*"还书:还书
    图书"*"--"1..*"管理员:管理图书信息
    读者"*"--"1..*"管理员:管理读者信息
    读者"*"--"1"注册登录
    管理员"*"--"1"注册登录
    读者"*"--"1..*"逾期罚款:逾期罚款
}
@enduml