@startuml

object 图书{
    书名="《西游记》"
    作者="吴承恩"
    出版社="成大出版社
    出版年份=2000
}
object 图书馆藏资源品种{
    资源名称="图书"
    单价=55.92
    简介="唐僧师徒西天取经"
    数量=22
    库存=15
    编号="A-123"
    是否可借=True
}
图书馆藏资源品种<|--图书
@enduml