@startuml
object 学生{
    学号="201510414413"
    年级=2015
    专业="软件工程"
}
object 老师{
    教师工号="XG-2202"
    教导课程编号="CU-238"
}
object 读者{
    姓名="梅恩"
    性别="男"
    用户名="meien643"
    密码="******"
    生日=1994.11
    年龄=29
    学院="信息科学与工程学院"
    个人头像
    个性签名="no"
}
读者<|--学生
读者<|--老师
@enduml