@startuml
hide footbox
title 基于GitHub的图书管理平台--学生列表用例顺序图
actor 用户 as user
alt
user->服务器:请求学生列表数据
服务器->服务器:判断是否登录
服务器->服务器:学生登录
服务器->数据库:请求学生列表
服务器->服务器:老师登录
服务器->数据库:请求学生列表加实验成绩
数据库->user:返回数据

'user->读者:读者是否登录
'user->借阅记录:获取读者借阅信息
'借阅记录->图书:选中目标图书并点击续借
'借阅记录->图书:是否已经续借过一次（最多一次）
'user->借阅记录:续借成功，归还时间增加
end alt
@enduml