@startuml
title 基于GitHub的实验管理平台--评定成绩用例的顺序图
actor 教师
== 查看成绩 ==
教师 -> 服务器 : 登录并选择课程
服务器->学生:查看学生列表
学生->实验:选择学生显示实验成绩
实验->评分项:显示对应实验的所有评分项
评分项->教师:已经批改的实验显示分数，未批改的则不显示
== 评定成绩 ==
教师 -> 评分项 : 给每个评分项填写成绩和评语
评分项->实验:系统根据评分项自动计算实验得分
实验->学生:系统根据实验自动计算学生平均实验得分
@enduml