@startuml

start
:输入账号;
:输入密码;
fork
:登录;
:选择读者或管理员身份;
if(账号是否存在？) then(是)
    if(账号密码是否正确？) then(是)
        :登录成功;
        :进入首页;
     else(否)
        :提示用户账号密码错误;
        :重新登录;
     endif;
else(否)
    :提示用户账号不存在;
    :重新登录;
endif;
fork again
:注册;
:再次确认密码;
:输入验证码;
if(账号是否存在？) then(是)
    :提示用户账号已存在;
    :注册失败;
else(否)
    if(两次输入的密码是否相同？) then(是)
        :注册成功;
        :返回登录页面;
    else(否)
        :提示用户两次密码不同;
        :重新注册流程;
    endif;
endif;
endfork
:登录注册流程结束;
stop;

@enduml