@startuml

start;
:读者登录;
:查询借阅信息;
:选择目标点击还书;
if(还书日期是否超时？) then(是)
    :计算超时金额;
    :读者缴纳超时金额;
endif;
:进入下一流程;
fork
if(书籍是否有损坏？) then(是)
    :根据损坏程度赔偿罚金;
    :缴纳罚金;
else(否)
    :还书成功;
    :将还书信息写入数据库;
endif;
fork again
if(书籍是否遗失？) then(是)
    :赔偿相应罚金;
else(否)
    :还书成功;
    :将还书信息写入数据库;
endif;
end fork
:还书流程结束;
stop;

@enduml